### ISSUE TITLE
set constraint names from @constraint macro

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#1166]
https://github.com/JuliaOpt/JuMP.jl/blob/c9200d7a108924bca2a703fcf122318675313933/src/macros.jl#L326

**Comment by blegat** [comment]
What should be the names for vectorized constraints ?
For
```julia
@constraint(model, con[i=1:2], x .== i)
```
the names are `con[1]` and `con[2]`.

For
```julia
@constraint(model, con, [x, y] .== [0.0, 0.0])
```
should the names be `con` and `con` or `con[1]` and `con[2]` ?

For
```julia
@constraint(model, con[i=1:2], [x, y] .== [i, i])
```
should the names be `con[1]`, `con[1]`, `con[2]` and `con[2]` or `con[1][1]`, `con[1][2]`, `con[2][1]` and `con[2][2]` ?

If we choose to use different names accross the broadcast, we will need to somehow get the index in the broadcasted function (or stop relying on broadcast but then many exotic cases might stop working).
If we choose to use the same name then we remove the possibility to query constraints per name when they are set with the broadcast syntax but that does not seem to be a very common use case.

**Comment by mlubin** [comment]
I don't have a clear answer for how to name the broadcasted constraints. I think using the same name for all of them is a reasonable first pass that we can refine later on if needed.

Removed from the 0.19 milestone. It would be nice to have, but this would be new functionality relative to 0.18 anyway.

**Comment by danielolsen** [comment]
I just found this thread and would like to reiterate my support for this feature. As a user, I would want a set of unique names, because I am running into issues trying to do exactly what you describe
> query constraints per name when they are set with the broadcast syntax
to get the shadow prices of a set of constraints which are created via matrix operations inside `@constraint`. My workaround is to manually set the names in a loop after the constraint is generated, which works, but it's not intuitive that this is necessary from the documentation at http://www.juliaopt.org/JuMP.jl/dev/constraints/#Vectorized-constraints-1.

For @blegat's example, I would prefer names like `con[1,1]`, `con[1,2]`, `con[2,1]`, and `con[2,2]`.

**Comment by odow** [comment]
Related issue: https://github.com/jump-dev/JuMP.jl/issues/1936
