### ISSUE TITLE
Support MOI modifications

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#1183]
http://www.juliaopt.org/MathOptInterface.jl/latest/apireference.html#Functions-and-function-modifications-1

**Comment by odow** [comment]
http://www.juliaopt.org/MathOptInterface.jl/latest/apireference/#Modifications-1

For now we have implemented
- [ ] ScalarConstantChange. Due to ambiguities, we have decided that this is best done by introducing a dummy variable and calling `JuMP.fix(variable)`. Still needs docs
- [ ] VectorConstantChange
- [x] ScalarCoefficientChange: https://github.com/JuliaOpt/JuMP.jl/pull/1351
- [ ] MultirowChange

**Comment by odow** [comment]
I vote that `VectorConstantChange` and `MultirowChange` are not blockers for 0.19. Can this issue be removed from that milestone?

**Comment by odow** [comment]
The only one missing is now `MultirowChange`. But it obviously isn't that important because I've never seen anyone ask for it.
