### ISSUE TITLE
Should SparseAxisArray be an AbstractDict?

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/JuMP.jl#2176]
Example of surprising behaviour:
```julia
julia> m = Model()
julia> S = 1:10
julia> @variable(m, x[i=10:20,s=S; i == s], Bin)
JuMP.Containers.SparseAxisArray{VariableRef,2,Tuple{Int64,Int64}} with 1 entry:
  [10, 10]  =  x[10,10]

julia> collect(x)
ERROR: MethodError: no method matching size(::JuMP.Containers.SparseAxisArray{VariableRef,2,Tuple{Int64,Int64}})
Closest candidates are:
  size(::AbstractArray{T,N}, ::Any) where {T, N} at abstractarray.jl:38
  size(::BitArray{1}) at bitarray.jl:77
  size(::BitArray{1}, ::Integer) at bitarray.jl:81
```

`AbstractArray` must normally implement `size` and `getindex`. Given the functions implemented, it would probably make more sense for `SparseAxisArray` to subtype AbstractDict (with `getindex(s, k::K)`

**Comment by odow** [comment]
This seems like a reasonable idea. There are a number of open issues relating to SparseAxisArrays, mainly relating to the fact that we call it an `Array`, but it doesn't implement the array interface.

**Comment by matbesancon** [comment]
Looking at the code base, it also looks like we are not leveraging the current sub-typing anywhere, I'll try to put together a PR

**Comment by blegat** [comment]
It's not really an `AbstractDict` either. An `AbstractDict` is like a vector of pairs mapping keys to values. It's length is the number of pairs and it has dimension 1.
The `SparseAxisArray` has dimension `N`, it has a size, which is the number of different key in each dimension but computing it is not O(1). We could precompute the size at construction since we go over all keys but it might not be the only think missing for `collect` to work.
What should be the result of calling `collect` on a `SparseAxisArray` ? It might be an `N`-dimensional array with missing entries that are filled with `missing` ?
If you want a dictionary interpretation of the `SparseAxisArray`, you can do `x.data`.

**Comment by matbesancon** [comment]
> but it might not be the only think missing for collect to work

as long as we have getindex and size defined all other array-related functions have fallbacks.

Not sure it does have the array semantics given that elements are missing, one cannot colon-subindex `arr[:,1]` nor multiply with another array of values

**Comment by blegat** [comment]
You could colon-index it, it would give a SparseAxisArray back.
Users write code on JuMP containers without worrying what is the type of the container. Hence SparseAxisArray should behave as closely to an array as possible. 
For users that know that what they have is a SparseAxisArray and want it to behave like a Dict, they should take x.data.

**Comment by jd-lara** [comment]
I am throwing this here since it might help the discussion. https://github.com/andyferris/Dictionaries.jl

**Comment by odow** [comment]
I think the answer to this is no. 

But we can make it easier to create dicts instead: https://github.com/jump-dev/JuMP.jl/issues/2523#issuecomment-821932919
