### ISSUE TITLE
Passing bounds before other constraints

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/JuMP.jl#2243]
(JuMP is possibly not the best repo for the issue, I'll move it if requested)
This error appeared with SOC constraints in SCIP:

JuMP version (same behaviour with Model instead of direct model)

```julia
using JuMP
import SCIP
using Test

m = direct_model(SCIP.Optimizer())

@variables(m, begin
    x
    y
    z
end)

@constraint(m, x == 1)
@constraint(m, [x, y, z] in SecondOrderCone()) 
```

Errors on the last line with:
```
SCIP needs non-negative variable on right-hand side of second-order cone constraint, have lower bound: -1.0e20!
in top-level scope at JuMP/CZ8vV/src/macros.jl:381
in add_constraint at JuMP/CZ8vV/src/constraints.jl:403
in moi_add_constraint at JuMP/CZ8vV/src/constraints.jl:391
in add_constraint at SCIP/lx725/src/MOI_wrapper/soc_constraints.jl:12
in error at base/error.jl:33
```

MOI version works fine:
```julia
model = SCIP.Optimizer()
x, y, z = MOI.add_variables(model, 3)
vov = MOI.VectorOfVariables([x,y,z])
MOI.add_constraint(model, x, MOI.EqualTo(1.0))
csoc = MOI.add_constraint(model, vov, MOI.SecondOrderCone(3))
MOI.set(model, MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}(), MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.([1.0,1.0], [y,z]), 0.0))
MOI.set(model, MOI.ObjectiveSense(), MOI.MAX_SENSE)
MOI.optimize!(model)
@test MOI.get(model, MOI.PrimalStatus()) == MOI.FEASIBLE_POINT
@test MOI.get(model, MOI.ObjectiveValue()) ≈ √2 atol = 10e-4
```

works all the way through.

I guess one workaround would be to let the user pass SOC constraints with unchecked bounds

```
(SOCTest) pkg> st
Status `~/Documents/crptests/project_julia/SOCTest/Project.toml`
  [4076af6c] JuMP v0.21.2 #master (https://github.com/JuliaOpt/JuMP.jl.git)
  [82193955] SCIP v0.9.5
```

(MOI v0.9.13)

**Comment by matbesancon** [comment]
ping @rschwarz in case I missed a trick from the SCIP hat :)

**Comment by rschwarz** [comment]
Yeah, this situation is not so nice. I noticed that when a SOC constraint is created in SCIP, it is `assert`ed that the lower bound of one variable (forgot the order) is non-negative.
So I just check for this in SCIP.jl as well, so that the user sees a Julia error message & stack trace, rather than some internals of the C library.

I also thought about implicitly setting that lower bound, when adding the constraint, but that requires another level of storage, or else bound queries don't work.

----

About the difference between MOI & JuMP here: I think that the constraint `x == 1` might be added as a linear constraint, rather than as fixed upper/lower bounds. So, your MOI version uses a scalar function, but JuMP an affine function?

**Comment by odow** [comment]
> About the difference between MOI & JuMP here: I think that the constraint x == 1 might be added as a linear constraint, rather than as fixed upper/lower bounds. So, your MOI version uses a scalar function, but JuMP an affine function?

Yes, the formulations are not the same. This behavior is expected.

**Comment by matbesancon** [comment]
Indeed the model works when x is defined with a positive bound

**Comment by odow** [comment]
Can this be closed since it is expected behavior?

**Comment by matbesancon** [comment]
yup I think so
