### ISSUE TITLE
Infer bounds on binary variables

### ISSUE THREAD

**Issue by hdavid16** [jump-dev/JuMP.jl#2288]
Having JuMP infer the bounds on binary variables would avoid unnecessary warnings in some solvers like CPLEX.

If a user specifies a variable as:
`@variable(model, x, Bin)`
This would be interpreted as
`@variable(model, 0 <= x <= 1, Bin)`

See the discussion in https://github.com/jump-dev/CPLEX.jl/issues/311#issuecomment-659441932

**Comment by odow** [comment]
I don't think this should happen. It's a variable with no bounds, that is inferred as belonging to `{0, 1}`. Variable bounds are a separate constraint.

In the first case, if you ask for `has_lower_bound(x)` on the first one it will return `false`. 

If you call `unset_binary(x)` in the first case, what should happen? Should it relax to `[0, 1]` or `[-Inf, Inf]`? If it is `[-Inf, Inf]`, then how do we tell the difference between `@variable(model, x, Bin)` and `@variable(model, 0 <= x <= 1, Bin)`. Because in the second case, `unset_binary(x)` will relax to `[0, 1]`.

This should just be fixed in the CPLEX wrapper so it doesn't throw the error.

**Comment by mlubin** [comment]
Agreed, the current behavior is intentional. It's up to the CPLEX wrapper to process binary variables appropriately so that the solver doesn't print warnings.
