### ISSUE TITLE
Expand documentation for user defined functions

### ISSUE THREAD

**Issue by KSepetanc** [jump-dev/JuMP.jl#2314]
In the documentation, there is no example how to add custom function for Hessian matrix.

I think it would be great to expand existing example for `my_f` ([link](https://jump.dev/JuMP.jl/v0.19.0/nlp/#User-defined-Functions-1)) with Hessian function.

**Comment by mlubin** [comment]
There's no example because this functionality isn't supported (https://github.com/jump-dev/JuMP.jl/issues/1198). The text says, "Second-order derivatives of multivariate functions are not currently supported".

**Comment by KSepetanc** [comment]
I have a problem for KNITRO solver that is bottlenecked with NL evaluation times. My NL constraints are long and mainly consisting of sqrt(norm2(x) + constant)/norm2(x), where x is a vector of 3 variables. I thought declaring this long expression as a function and providing analytical expressions for Jacobian and Hessian would speed-up evaluations. Do you have experience with that? Would it speed-up NL evaluations?

I missed the sentence that is not supported. Does that mean that even automatic Hessian is not supported? Also, does that mean that custom functions in multiple variables can not be used with KNITRO which I think needs Hessian?

Do you know if AMPL can define new functions with Jacobian and Hessian for NL optimization? What modeling language would you recommend for that if AMPL does not support it?

**Comment by mlubin** [comment]
> My NL constraints are long and mainly consisting of sqrt(norm2(x) + constant)/norm2(x), where x is a vector of 3 variables. I thought declaring this long expression as a function and providing analytical expressions for Jacobian and Hessian would speed-up evaluations. Do you have experience with that? Would it speed-up NL evaluations?

Using user-defined functions when your constraints are simple closed-form algebraic expressions like these will *not* speed up evaluations in general. AD is already fast in this case. Try reformulating the expression so that the Hessian is sparser and the AD system has to do less work, for example, define `t == norm2(x)` (this is a quadratic constraint, no AD needed) and write `sqrt(t + constant) / t`. This avoids duplicate computation of `norm2(x)` and gives a sparser Hessian matrix. You can also try using second-order cone constraints if the model allows it (impossible to tell given the information provided).

> Does that mean that even automatic Hessian is not supported?

Hessian computations are disabled when the model has multivariate user-defined functions.

> Also, does that mean that custom functions in multiple variables can not be used with KNITRO which I think needs Hessian?

KNITRO does not require Hessians, although there are algorithmic implications of not providing them.

> Do you know if AMPL can define new functions with Jacobian and Hessian for NL optimization?

Probably, but you'd have to check the AMPL documentation.

**Comment by KSepetanc** [comment]
I will be closing this issue since it exists as more basic issue #1198 .
I can only express support and emphasize usefulness of allowing to provide Hessians for custom functions.
Hope you implement it soon.
