### ISSUE TITLE
Source links in solutions.md

### ISSUE THREAD

**Issue by remi-garcia** [jump-dev/JuMP.jl#2358]
On the doc page for [Query Solutions](https://jump.dev/JuMP.jl/stable/solutions/) some source buttons link to the julia GitHub. I have not been able to find the reason of this behavior, sorry.
![Screenshot from 2020-10-22 15-58-54](https://user-images.githubusercontent.com/47191601/96882817-f9d7be80-147f-11eb-8b60-d8ebc50b5d78.png)

**Comment by odow** [comment]
This is pretty weird. Might be a bug in documenter?

**Comment by odow** [comment]
Here's the issue: https://github.com/JuliaDocs/Documenter.jl/issues/1374.
Fixed upstream: https://github.com/JuliaLang/julia/pull/37048

It's due to the docstring being attached to a macro (in this case, `@enum`s).

We can use this work-around https://github.com/JuliaDocs/Documenter.jl/issues/1374#issuecomment-668363902, or just wait for a new Julia version.

**Comment by odow** [comment]
Closing as fixed upstream. I don't think we need the work-around.
