### ISSUE TITLE
NLP parser assumes `::Model` and violates MethodError principle

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2402]
`_process_NL_expr` gets called from the `@NL` macros, and doesn't have any type requirements:
https://github.com/jump-dev/JuMP.jl/blob/1e6b5d8542e50a06a67d41f4ded07394be62ddef/src/parse_nlp.jl#L233
but it eventually calls a `_process_NL_expr_runtime` which are restricted to `::Model`.
https://github.com/jump-dev/JuMP.jl/blob/1e6b5d8542e50a06a67d41f4ded07394be62ddef/src/parse_nlp.jl#L181

Thus, someone (e.g., BilevelJuMP, x-ref: https://github.com/joaquimg/BilevelJuMP.jl/issues/57) using this machinery with an `<:AbstractModel` encounters a MethodError:
https://discourse.julialang.org/t/methoderror-no-method-matching-parse-nl-expr-runtime-bilevel-problem/51681

We could either add a type-restriction to `_process_NL_expr` and have a fallback with an informative error message, or we could probably relax the type-restrictions, and see what happens. It probably means relaxing this as well to `AbstractVariableRef`:
https://github.com/jump-dev/JuMP.jl/blob/1e6b5d8542e50a06a67d41f4ded07394be62ddef/src/parse_nlp.jl#L187-L188

cc @pulsipher who might be messing with this stuff

**Comment by pulsipher** [comment]
This has indeed come up with InfiniteOpt.jl as I've looked into how to enable NLP expressions (see https://github.com/pulsipher/InfiniteOpt.jl/issues/16). At one point, I did make a version of  `_parse_NL_expr_runtime` that could work with `InfiniteModel`s and my variable types, however I ran into a number of other problems further down the NLP pipeline. 

Thus, I came to the conclusion that the JuMP NLP interface in its current form is essentially non-extendable without a significant rewrite such as what is proposed in https://github.com/jump-dev/MathOptInterface.jl/issues/846. Since this is a long way out, I am actually looking into developing a native NLP expression tree abstraction to InfiniteOpt.jl to enable NLP expressions/constraints. 

For what it is worth, my recommendation here would be to add a meaningful fallback method and reserve any additional effort for use toward https://github.com/jump-dev/MathOptInterface.jl/issues/846 once the time comes to work on it.
