### ISSUE TITLE
Container with a dictionary as the dimension

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2424]
@geoffleyland found this wonderfully confusing example:

```Julia

julia> d = Dict("a" => 1, "b" => 2)
Dict{String,Int64} with 2 entries:
  "b" => 2
  "a" => 1

julia> model = Model();

julia> @variable(model, x[(k, v) in d])
1-dimensional DenseAxisArray{VariableRef,1,...} with index sets:
    Dimension 1, Dict("b" => 2,"a" => 1)
And data, a 2-element Array{VariableRef,1}:
 x[("b", 2)]
 x[("a", 1)]

julia> x[("a", 1)]
ERROR: KeyError: key ("a", 1) not found
Stacktrace:
 [1] getindex at ./dict.jl:467 [inlined]
 [2] lookup_index at /Users/oscar/.julia/packages/JuMP/qhoVb/src/Containers/DenseAxisArray.jl:140 [inlined]
 [3] _to_index_tuple at /Users/oscar/.julia/packages/JuMP/qhoVb/src/Containers/DenseAxisArray.jl:149 [inlined]
 [4] to_index at /Users/oscar/.julia/packages/JuMP/qhoVb/src/Containers/DenseAxisArray.jl:167 [inlined]
 [5] getindex(::JuMP.Containers.DenseAxisArray{VariableRef,1,Tuple{Dict{String,Int64}},Tuple{Dict{Pair{String,Int64},Int64}}}, ::Tuple{String,Int64}) at /Users/oscar/.julia/packages/JuMP/qhoVb/src/Containers/DenseAxisArray.jl:182
 [6] top-level scope at REPL[68]:1

julia> x["a" => 1]
x[("a", 1)]
```

I'm not sure if this is intended or not. It makes sense when you think through what is happening, but it isn't obvious! This should either be documented, or fixed so that the pair is added as a tuple.

**Comment by fonterrageoff** [comment]
Thanks Oscar!

So this is not what I thought the problem was at all (I guessed tuples were being compared by reference).  But I'm curious:
```
julia> d = Dict("a" => 1, "b" => 2)
Dict{String,Int64} with 2 entries:
  "b" => 2
  "a" => 1

julia> [(k, v) for (k, v) in d]
2-element Array{Tuple{String,Int64},1}:
 ("b", 2)
 ("a", 1)

julia> [k=>v for (k, v) in d]
2-element Array{Pair{String,Int64},1}:
 "b" => 2
 "a" => 1
```

But in the variable indices case `[(k, v) in d]` yields pairs, not tuples? (rather than `[k => v in d]`, which I would expect to yield pairs).

In case it's of interest, the motivation behind trying this in the first place was that, given a Dict `d`, often find myself writing:
```
@variable(M, v[k in keys(d)] >= 0)
@constraint(M, c[k in keys(d)], v[k] <= d[k])
```
and it would be nicer to write:
```
@constraint(M, c[(k, b) in d], v[k] <= b)
```
as you can do in a `sum`.  It's not very compelling in this case, but when `d` is actually `struct.field.bounds` it gets wordy.

The intent here would be that `c` would be indexed by `k` alone (ie `M[:c]["a"]` would work, rather than `M[:c][("a", 1)]` or `M[:c]["a"=>1]`), but I'm not sure that matters.

(I'm aware I could just write the constraint above with a bound, but you get the point).

**Comment by odow** [comment]
For constraints, you are probably better with
```Julia
for (k, b) in d
    @constraint(M, x[k] <= b)
end
```
I don't really see how we could distinguish that you want `c` to be indexed by `k` but not `b`.

The real issue is that it is surprising these two things produce the same object, but with different names:
```julia
julia> @variable(model, x[k in d])
1-dimensional DenseAxisArray{VariableRef,1,...} with index sets:
    Dimension 1, Dict("b" => 2,"a" => 1)
And data, a 2-element Array{VariableRef,1}:
 x["b" => 2]
 x["a" => 1]

julia> @variable(model, y[(k, v) in d])
1-dimensional DenseAxisArray{VariableRef,1,...} with index sets:
    Dimension 1, Dict("b" => 2,"a" => 1)
And data, a 2-element Array{VariableRef,1}:
 y[("b", 2)]
 y[("a", 1)]
```
I would argue, it would be less surprising if `y` printed `y["b" => 2]`, or if both produced tuples, rather than pairs.

**Comment by fonterrageoff** [comment]
I think it's ok for `x` to be pairs, since that's what it was given, but it's surprising that `y` is.  For `y`, I think the right thing is to use tuples rather than pairs, but if that's too hard, then at least it should have output that looks like `x`.

You could, though, ask what a user might mean by making a distinction between pairs and tuples, figure that they probably didn't mean anything, and decide to always store pairs as tuples.  If a user did something like this:
```
@variable(model, x[k=>v for (k, v) in d])
@variable(model, x[(k, v) in d])
```
you could fairly reasonably argue that making a distinction between the pair and tuple indexes in the model is not the kind of thing that helps with model clarity.

By the way, thanks for the constraint suggestion.  For some reason I assumed that you couldn't make several @constraints with the same name but different indexes.  Now that you've shown me, it's obvious, and much tidier :-).

**Comment by odow** [comment]
> I assumed that you couldn't make several @Constraints with the same name but different indexes

You can't. But you can use an anonymous constraint (i.e., not named). In general, you should probably only name constraints if you want to look them up later. You could always store them in a different data-structure if that was easier.
```Julia
cons = Dict()
for (k, b) in d
    cons[k] = @constraint(M, x[k] <= b)
end
```

**Comment by odow** [comment]
Here's a similar example:
```Julia
julia> I = [ [0, 2] ]
1-element Array{Array{Int64,1},1}:
 [0, 2]

julia> model = Model();

julia> @variable(model, x[(i, j) in I])
1-dimensional DenseAxisArray{VariableRef,1,...} with index sets:
    Dimension 1, Array{Int64,1}[[0, 2]]
And data, a 1-element Array{VariableRef,1}:
 x[(0, 2)]

julia> x[(0, 2)]
ERROR: KeyError: key (0, 2) not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] lookup_index at /Users/oscar/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:145 [inlined]
 [3] _to_index_tuple at /Users/oscar/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:154 [inlined]
 [4] to_index at /Users/oscar/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:174 [inlined]
 [5] getindex(::JuMP.Containers.DenseAxisArray{VariableRef,1,Tuple{Array{Array{Int64,1},1}},Tuple{Dict{Array{Int64,1},Int64}}}, ::Tuple{Int64,Int64}) at /Users/oscar/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:192
 [6] top-level scope at none:0

julia> x[[0, 2]]
x[(0, 2)]
```

**Comment by odow** [comment]
Once #2524 is merged, one work-around is to define something like

```Julia
# Implement a special case: If the axis is a vector of pairs, also allow tuples as indices.

function Base.getindex(
    x::_AxisLookup{Dict{Pair{A,B},Int}},
    key::Tuple{A,B},
) where {A,B}
    return x.data[key[1] => key[2]]
end

function Base.getindex(
    x::_AxisLookup{Dict{Pair{A,B},Int}},
    keys::AbstractVector{<:Tuple{A,B}},
) where {A,B}
    return [x[key] for key in keys]
end

function Base.get(
    x::_AxisLookup{Dict{Pair{A,B},Int}},
    key::Tuple{A,B},
    default,
) where {A,B}
    return get(x.data, key[1] => key[2], default)
end
```

We should also add a `collect` to the axes, so that 

```julia
_collect(x::AbstractVector) = x
_collect(x) = [a for a in x]
function DenseAxisArray(data::Array{T,N}, axs...) where {T,N}
    @assert length(axs) == N
    new_axes = _collect.(axs)
    return DenseAxisArray(data, new_axes, build_lookup.(new_axes))
end
```
so we get a vector as the dimension, and not a `Dict`:
```Julia
julia> @variable(model, x[(k, v) in d])
1-dimensional DenseAxisArray{VariableRef,1,...} with index sets:
    Dimension 1, ["b" => 2, "a" => 1]
And data, a 2-element Vector{VariableRef}:
 x[("b", 2)]
 x[("a", 1)]
```
