### ISSUE TITLE
Add an `@register` macro

### ISSUE THREAD

**Issue by dpsanders** [jump-dev/JuMP.jl#2606]
The current `register` function has redundancy in the name of the function that could be nicely removed by adding an `@register` macro. 

In addition this would make the interface more consistent.

**Comment by odow** [comment]
So the ask is for
```Julia
@register(model, square, 1; autodiff = true)
```
instead of 
```Julia
register(model, :square, 1, square; autodiff = true)
```

I'm not a big fan of this for the sake of a few extra characters.

Registering functions is now optional, and a nice error is thrown explaining the syntax to copy-paste. 

The friction of registering a function also has a side benefit of steering people away from user-defined functions. Until we symbolically trace functions, JuMP looses a lot of performance from user-defined functions.

**Comment by dpsanders** [comment]
OK, thanks. The docs at https://jump.dev/JuMP.jl/v0.21.1/nlp/#:~:text=JuMP%20has%20support%20for%20general,improve%20solver%20accuracy%20and%20performance
state that "user-defined functions may be used only after they are registered".

Maybe add "JuMP will attempt to do so automatically".

I also did not realise / see in the docs that doing so is a performance issue.

**Comment by dpsanders** [comment]
I actually would suggest the syntax

```
@register(model, square(x))
```

**Comment by odow** [comment]
> https://jump.dev/JuMP.jl/v0.21.1/nlp/

That is an old documentation link. How did you find it? Here's the latest:
https://jump.dev/JuMP.jl/stable/manual/nlp/#User-defined-Functions

**Comment by odow** [comment]
The performance thing is https://github.com/jump-dev/JuMP.jl/issues/1198

**Comment by dpsanders** [comment]
Googling "jump nonlinear modelling" took me to that page. Actually now it's even worse -- it sends me to v0.19...

**Comment by mlubin** [comment]
We forgot to copy this over to jump.dev: https://github.com/JuliaOpt/juliaopt.github.io/blob/master/robots.txt

**Comment by odow** [comment]
Closing this as won't-fix. 

We're aware that registering functions is less than ideal, and it's something to consider when we rewrite JuMP's NLP support in JuMP 2.0.

For JuMP 1.0, we've also tried not to introduce additional macros when a function also works. And `@register(model, f(x, y))` could be equally confusing if you want to register derivatives, and because `x` and `y` don't need to be exit. It also makes `@register(model, f(x...))` hard if there are a large number of arguments; you don't want to write `@register(model, f(x1, x2, x3, x4, x5))` and so on.
