### ISSUE TITLE
Dual value computation / convention?

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/JuMP.jl#2640]
working on an SDP which looks like:

```
min_{lambda, A_i} lambda
lambda >= cste_j + sum_i dot(A_i, C_ij) forall j
A_i SDP forall i
```

The problem does not appear on small-enough sizes so I included a gist here with the MOF file: https://gist.github.com/matbesancon/6a70282902e0ef7268b5c2f7f71065dc

```julia
using JuMP, SCS, LinearAlgebra
for max_iters in [10, 30, 100, 300, 1000, 3000, 1000]
    m = read_from_file("SDPs/SDP_K3K3c_345.mof.json")
    set_optimizer(m, optimizer_with_attributes(SCS.Optimizer, "verbose" => 0, "max_iters" => max_iters))
    optimize!(m);
    println("$(max_iters): primal $(objective_value(m)) and dual $(dual_objective_value(m))")
end
```
Output:
```
10: primal -0.1527555771736167 and dual -0.0786107937488518
30: primal -0.1387804952651251 and dual -0.09817944313524096
100: primal -0.24245622670335407 and dual -0.27623096565969085
300: primal -0.24973888464914104 and dual -0.2483521497705304
1000: primal -0.2500017776695332 and dual -0.25006703864156454
3000: primal -0.2500006404428662 and dual -0.25000544317338264
1000: primal -0.2500017776695332 and dual -0.25006703864156454
```

Why is this surprising:
The dual objective value (maximization problem) is decreasing with the number of iterations, and it seems not to be a valid lower bound for the actual optimal value, is this expected?

**Comment by joaquimg** [comment]
JuMP/MOI simply forward what the solver says.
In the case of SCS...
The MOI wrapper:

https://github.com/jump-dev/SCS.jl/blob/500e75d8f3a3467b8ae2814a49e41aa05c31439e/src/MOI_wrapper.jl#L270
 
 Forwards the output of the C API that returns in `infor_ref`:
 
 https://github.com/jump-dev/SCS.jl/blob/500e75d8f3a3467b8ae2814a49e41aa05c31439e/src/c_wrapper.jl#L78
 
 So this value is just the current:
 `dot(y, b)` where `y` is dual and `b` is the rhs of constraints.

The problem is probably (dual) feasibility.
The solution might be far from (dual) feasible.

**Comment by matbesancon** [comment]
oh I see ok, this is not a primal-dual pair that are both maintained feasible, thanks
