### ISSUE TITLE
Large SparseAxisArrays get stuck on `show`

### ISSUE THREAD

**Issue by raphaelsaavedra** [jump-dev/JuMP.jl#2683]
Not sure if this is a known issue, I have found https://github.com/jump-dev/JuMP.jl/pull/2630 which seems somewhat related to this.

When I have a very large `SparseAxisArray` and I (accidentally or not) try to show it in the REPL, the following is printed in the REPL:

```
SparseAxisArray{Float64, 2, Tuple{String, Int64}} with 115134138 entries:

```

and it just takes forever and gets stuck. I end up having to kill the terminal.

**Comment by odow** [comment]
Yes, presumably this is the cause:
https://github.com/jump-dev/JuMP.jl/blob/c9e7a894524fdbeecd98c3426d4ab4123dc07fb9/src/Containers/SparseAxisArray.jl#L289-L304

Something like figuring out the maximum length of a key when there are 115 million entries is a lot of work...

We should filter the rows that are printed up-front, and then only loop through those, rather than checking with the `print_entry` function.

**Comment by blegat** [comment]
I guess we could improve things here:
https://github.com/jump-dev/JuMP.jl/blob/c9e7a894524fdbeecd98c3426d4ab4123dc07fb9/src/Containers/SparseAxisArray.jl#L284-L287
1) `typemax(Int)` by default seems to be a lot
2) Why do we create this filter `print_entry` and `key_strings` with all the entries and not just `key_strings` with only the entry we want to print directly ? It seems to be because we want stable selection of the entries we print that does not depend on the order of the dictionary. However,  `join(key, ", ")` might allocate a lot
