### ISSUE TITLE
Make delete, is_valid and set_objective_coefficient consistent with other methods

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/JuMP.jl#2769]
All three: `delete`, `is_valid` and `set_objective_coefficient`
require the model as a first argument,
but all other methods like:
`start_value`, `value`, `set_integer`, `name`, `set_name`, `set_normalized_coefficient`, `set_normalized_rhs` etc
do *not* require the model a first keyword.

For the case of `is_valid`, one could argue that it check if it's valid for the model, buts there is already `check_belongs_to_model`.

**Comment by odow** [comment]
Closing because this is extra breakage that we don't need. 
 * `delete(model, x)` is okay, is already widely used, and is overloadable by extensions.
 * `is_valid` has a legitimate use-case that is different from `check_belongs_to_model`
 * `set_objective_coefficient(model, x, c)`  is okay, is already widely used, and is overloadable by extensions.
