### ISSUE TITLE
Refactor print to using printing implemented for MOI backend

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#2814]
Adding it in the v1.0 milestone as it might change a bit the printing so it's best to do it now.

**Comment by odow** [comment]
I considered this, but I decided there were enough issues to justify duplicating the code. Particularly around nonlinear

**Comment by blegat** [comment]
For issues, 1, 4 and 5, this can be resolved by having a more flexible printing at the MOI level, I had this flexibility in https://github.com/jump-dev/MathOptInterface.jl/pull/1180.
For 3, I agree, if the MOI printing is flexible enough, the JuMP printing does not have to change too much.
For 2, the nonlinear part of printing can stay at the JuMP level for the moment.

**Comment by odow** [comment]
The JuMP printing code _could_ be tidied up, and leverage a lot of the `MOI.Utilities._to_string` calls, but I don't think we should make major changes. Things are working well as-is. and we haven't needed to touch the code in ages. 

Duplicating code between JuMP and MOI isn't necessarily a bad thing.

**Comment by blegat** [comment]
We would need https://github.com/jump-dev/MathOptInterface.jl/pull/1695 to be applied to JuMP as well for https://github.com/jump-dev/JuMP.jl/pull/2391.
So we might as well directly print the MOI function instead of converting it to an `AffExpr` and then print it, this would also be faster.

**Comment by odow** [comment]
Yes, you could use MOI to print the MOI function. Except for the `noname` issue. I don't think we really care about speed. Printing the JuMP model will never be in a critical path.

**Comment by joaquimg** [comment]
minor piece of this issue,
could we print: `noname[$(vi.value)]` instead of just `noname`?

**Comment by blegat** [comment]
> could we print: `noname[$(vi.value)]` instead of just `noname`?

This of the features I would like added to the printing. One may would be to make it easy from MOI to determine how unnamed variable are printed, e.g., via a function as I did in https://github.com/jump-dev/MathOptInterface.jl/pull/1180. Then JuMP would give by default `_ -> noname` but the user could pass a function to JuMP that is passed to MOI to overwrite that. I usually want to give `vi -> "x[vi.value]"` except when I have variables `x` then I name it differently. This shows that the user needs to specify that since there is no good default that works for all use cases.

**Comment by odow** [comment]
So I went through the printing file carefully in #2820.

In the main, I don't think we should make changes to the printing. There's ~90 lines associated with printing JuMP variables and expressions that could be forwarded to MOI. But this code never gets touched, so it isn't really a problem.

There is another ~30 lines for the set printing that could also get forwarded to MOI. But then we get printing like "in Zeros(2)" instead of `in MathOptInterface.Zeros(2)" which obscures where the sets are coming from. It's another case of not a major problem. 

The nonlinear stuff is all totally different because of parameters and subexpressions, so no win there. 

The model printing is different because we need to print parameters and subexpressions, and for it to work with extensions. The functions are reasonably simple, so there's not much of a win to over-complicate the MOI functions in order to save a few lines in JuMP.

REPLMode and IJuliaMode are harder. It'd be nice to replace `::Type{REPLMode}` with `::MIME"text/plain"`. That could be a breaking JuMP-1.0 change that I'd support. If we don't want to break things then things are okay as they are. There's no pressing need to change them.

> could we print: noname[$(vi.value)] instead of just noname?

How about `anon[$(x.value)]`? It is a bit of a pain being unable to distinguish different anonymous variables.

> Then JuMP would give by default _ -> noname but the user could pass a function to JuMP that is passed to MOI to overwrite that

This is too complicated. Where would this function be passed? No one has complained about `noname` (and no one will probably complain about `anon[1]`). At the MOI-level people can change what the default variable name is.

**Comment by joaquimg** [comment]
> How about `anon[$(x.value)]`? 

`anon[$(x.value)]` is good for me.

**Comment by blegat** [comment]
> REPLMode and IJuliaMode are harder. It'd be nice to replace `::Type{REPLMode}` with `::MIME"text/plain"`. That could be a breaking JuMP-1.0 change that I'd support. If we don't want to break things then things are okay as they are. There's no pressing need to change them.

Yes, having the same printing option struct with MOI could be nice

**Comment by odow** [comment]
I took a further look at this. Lots of extensions are using REPLMode and IJuliaMode, so I'm not convinced the breakage is worth it. We also don't want to use the same printing option struct, because then if we add an option to MOI we'll have to replicate the same option in JuMP.

I'm actually reasonably happy with the current state of printing, so I'd be in favor of closing this issue.

**Comment by blegat** [comment]
> We also don't want to use the same printing option struct, because then if we add an option to MOI we'll have to replicate the same option in JuMP.

By same printing option I mean the same struct, no need to replicate the struct in JuMP

**Comment by odow** [comment]
Revisiting how we print things could be a JuMP 2.0 issue. But I think for now things work, the code is pretty readable, and I don't want to make breaking changes.

Objections to closing this issue?

**Comment by odow** [comment]
Talked to @blegat. The request is to break and change `REPLMode` to `MIME"text/plain"` and `IJuliaMode` to `MIME"text/latex"`. 

This affects quite a few JuMP extensions, but it's a find-and-replace for JuMP 1.0 support.
