### ISSUE TITLE
Boolean variable for postprocessing if the optimization is optimal

### ISSUE THREAD

**Issue by ga72kud** [jump-dev/JuMP.jl#2951]
Thank you for the awesome package. I am trying to figure out: How to get the boolean value if the optimation is optimal and only this variable? 	JuMP.set_optimizer_attribute(mpc, "print_level", 0)

JuMP.termination_status(mpc) gives 

JuMP.termination_status(mpc) = MathOptInterface.LOCALLY_SOLVED
JuMP.termination_status(mpc) = MathOptInterface.LOCALLY_INFEASIBLE

Is there a best practice to figure out why it was infeasible and which constraints were not fullfilled

**Comment by odow** [comment]
> How to get the boolean value if the optimation is optimal and only this variable?

See https://jump.dev/JuMP.jl/stable/manual/solutions/#Recommended-workflow

You probably want 
```
is_optimal = JuMP.termination_status(mpc) == LOCALLY_SOLVED
```

> Is there a best practice to figure out why it was infeasible and which constraints were not fullfilled

Since it looks like you're solving a nonlinear program, the answer is no. (Some solvers support conflicts, https://jump.dev/JuMP.jl/stable/manual/solutions/#Conflicts, but Ipopt isn't one of them.)

You could try:
 * Providing a better starting point. The status is `LOCALLY_INFEASIBLE`, which doesn't mean that there isn't a feasible solution somewhere, only that the solver couldn't find one.
 * Commenting out constraints one-by-one.
 * Adding slack variables to each constraint, and then penalizing their sum. Instead `x <= 1`, do `x <= 1 + penalty` and then minimize `penalty`.

p.s. In future, please post usage questions like this on the community forum: https://discourse.julialang.org/c/domain/opt/13. We keep the GitHub issues for bug reports and feature requests. Posting on the community forum also means that the answers may help other people in future who have similar questions.

**Comment by odow** [comment]
I'm going to close this because it seems resolved. Please post in the community forum if you're still having trouble and we can discuss further.
