### ISSUE TITLE
Lower bound identifiable by MOI.Interval

### ISSUE THREAD

**Issue by guilhermebodin** [jump-dev/JuMP.jl#3023]
Hello! I am running codes such as this one
```julia
using JuMP
model = Model()
@variable(model, x in MOI.Interval{Float64}(0.1, 0.8))
@variable(model, y in MOI.LessThan{Float64}(0.8))
@constraint(model, y in MOI.GreaterThan{Float64}(0.1))
lower_bound(x) # Errors
lower_bound(y)
upper_bound(y)
```
but it says that the variable `x` has no lower bound because it only considers the `GreaterThan` constraints as indicators for lower bound. Is it possible to consider the Interval constraint as bounds for the variable too?

**Comment by odow** [comment]
The main reason is that JuMP doesn't pass `Interval` constraints to the solver. `@variable(model, 1 <= x <= 2)` passes a `LessThan` and a `GreaterThan`. So that's why you can query and modify them independently. 

In that sense, `lower_bound` is really "the GreaterThan constraint" and `upper_bound` is "the LessThan constraint."

Is there any reason to use `Interval` directly?

**Comment by guilhermebodin** [comment]
hmm very good point, this makes the bounds independent.

Well, my motivation is because defining `@variable(model, x in MOI.Interval{Float64}(0.1, 0.8))` can be more performant in the Xpress wrapper. When we create a new variable we can define the upper and lower bounds on the variable creation. If we create a variable and then 2 constraints we would have to call 3 functions of Xpress instead of only one. 

The case is that when I create variables directly in MOI.Interval I am unable to query their bounds using the JuMP interface, although it is not complicated to create a function that makes the query using the MOI interface.

In this case, what would be useful is a JuMP function that can retreive the set that a given variable was constrained on creation, but I understand that this can have some very weird corner cases and might not be desirable.

**Comment by odow** [comment]
> Well, my motivation is because defining @variable(model, x in MOI.Interval{Float64}(0.1, 0.8)) can be more performant in the Xpress wrapper

> If we create a variable and then 2 constraints we would have to call 3 functions of Xpress instead of only one.

I didn't dig into those benchmarks you did, but I assume this can be fixed in the Xpress wrapper? Where is the bottleneck? Is it really problematic? Does Xpress implement a fast `copy_to` for the first solve?

> what would be useful is a JuMP function that can retreive the set that a given variable was constrained on creation

Hmm. I see the point, but this could be tricky. It's also slightly weird in that you typically can't delete or modify the constraints. Variables constrained on creation are really intended for solvers that support special types of variables that aren't free, like CSDP supporting non-negative and Mosek supporting PSD matrices.

**Comment by guilhermebodin** [comment]
Hmm, currently I am using the direct mode. The Xpress copy_to is the default_copy_to but I could try to make an implementation in the near future.

The main bottleneck is that adding variables in batches and with the bounds is way better than adding variables one by one and then adding constraints to represent the bounds. Thanks for the comment @odow, I am closing as I think that indeed there are other ways to handle better my problem here.

**Comment by mlubin** [comment]
Yeah I'd recommend sticking to the MOI workarounds. This is a sufficiently narrow use case that it's not worth redefining what we mean by `lower_bound` and `upper_bound`.
