### ISSUE TITLE
Heads-up: Resolution of a broken test upcoming

### ISSUE THREAD

**Issue by dkarrasch** [jump-dev/JuMP.jl#3348]
I just wanted to let you know that it turns out that https://github.com/JuliaLang/julia/pull/43972 will resolve

https://github.com/jump-dev/JuMP.jl/blob/ff3917aa2ad2f071efa4aaefdd4a701caf20ae66/test/test_linear_algebra.jl#L84

So at some point, this broken test may need a little version-adoption (`VERSION >= v"1.10-"`) or something. Cheers!

**Comment by odow** [comment]
Thanks for the heads up. We test on nightly, so once https://github.com/JuliaLang/julia/pull/43972 gets merged we can fix then. It's always nice to have `@test_broken` suddenly start working :smile:.

I don't know if we need to keep this issue open since we test on nightly and the ETA for it landing seems uncertain. (Hopefully soon, but it's been 18 months...)

**Comment by odow** [comment]
Closing for now. I'll correct the test once the PR makes it into a nightly build.

**Comment by odow** [comment]
@dkarrasch see https://github.com/jump-dev/JuMP.jl/pull/3351

Thanks for fixing this!
