### ISSUE TITLE
Bullet point alignment in bibliography

### ISSUE THREAD

**Issue by jd-foster** [jump-dev/JuMP.jl#3704]
Something strange is happening with the alignment of the bullets (only visible in dark mode??)

<img width="258" alt="image" src="https://github.com/jump-dev/JuMP.jl/assets/38274066/8488e93b-afe3-4a6c-8086-95f0fca4b956">

Feel free to close, this is possibly a Documenter issue.

**Comment by odow** [comment]
cc @goerz have you noticed this before?

Link: https://jump.dev/JuMP.jl/stable/background/bibliography/

**Comment by goerz** [comment]
I have not noticed this before (maybe because I don’t use dark mode), but seems like a CSS problem. I’ll have a look

**Comment by goerz** [comment]
I'm also seeing this in https://juliadocs.org/DocumenterCitations.jl/stable/gallery/#author_year_style

So it's not specific to any kind of JuMP settings, but something that should be fixed in the ["recommended" CSS](https://juliadocs.org/DocumenterCitations.jl/stable/styling/). The bullet point is just supposed to be invisible, but it seems to clash with something in the dark mode CSS.

**Comment by goerz** [comment]
Yeah, `documenter-dark.css` is overriding the `list-style: none` in `citations.css` with `list-style: disc outside`.

![CleanShot 2024-03-08 at 12 23 34@2x](https://github.com/jump-dev/JuMP.jl/assets/112306/68f13e9a-26ff-446e-80c1-0f562d21a4b2)

I guess it's because the `documenter-dark.css` gets loaded later? Maybe we have to mark the `citatations.css` settings as "important".

**Comment by goerz** [comment]
Adding `important` to the `citations.css` seems to do the trick:

```css
.citation ul {
 padding: 0 0 2.25em 0;
 margin: 0;
 list-style: none !important;}
```

I'll make a `DocumenterCitations` release with a new recommendation for the CSS, but you'll have to change the `citations.css` file manually in your existing documentation (probably directly on the `gh-pages` branch).

**Comment by goerz** [comment]
This is "fixed" in the `DocumenterCitations` [release `v1.3.3`](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/master/NEWS.md#version-133---2024-03-08) I just made. Although updating `DocumenterCitations` won't really do anything for you: you'll have to modify https://github.com/jump-dev/JuMP.jl/blob/master/docs/src/assets/citations.css (and also the `citations.css` in existing deployed versions of your documentation)

**Comment by shayandavoodii** [comment]
Would adding the `!important` to the `citations.css` of the dev version also result in fixing the upcoming versions? I want to ensure that no other `.css` modification is required for future releases, and the change will automatically be applied to the upcoming releases.

**Comment by odow** [comment]
> Would adding the !important to the citations.css of the dev version also result in fixing the upcoming versions?

#3706 edits `master`. That'll fix the `dev` docs and all future versions. It won't fix already published versions.

**Comment by shayandavoodii** [comment]
> > Would adding the !important to the citations.css of the dev version also result in fixing the upcoming versions?
> 
> #3706 edits `master`. That'll fix the `dev` docs and all future versions. It won't fix already published versions.

Thank you so much. I got it.
