### ISSUE TITLE
Stack overflow error when find the value of deeply nested nonlinear expressions

### ISSUE THREAD

**Issue by mitchphillipson** [jump-dev/JuMP.jl#3884]
As the title says, finding the value of a deeply nested nonlinear expression causes a stack overflow error. I've minimized the value of `N` on my machine.

MWE:
```julia
using JuMP
M = Model()
N = 8_000
@variable(M, x[1:N], start = 0)

# This line will fail
value(start_value,prod(sum(x[1:i]) for i in 1:N))

# Works as expected
value(start_value, @expression(M, prod(sum(x[1:i]) for i in 1:N)))
```

This is not urgent on my end, I moved the value inside the product. I am also refactoring my code to not have this issue.

**Comment by odow** [comment]
Issue is the use of recursion in

https://github.com/jump-dev/JuMP.jl/blob/7111683501f6792d2cac2e1bee863df9b96ed2ab/src/nlp_expr.jl#L694-L722

**Comment by odow** [comment]
So, taking another look, it's true that we use recursion in `value`. But the bigger issue is that you didn't use `@expression` to build the expression.

If you don't want to use `@expression`, call `flatten!` to lift the deeply nested expressions.
```julia
using JuMP
N = 8_000
model = Model()
@variable(model, x[1:N], start = 0)
f = prod(sum(x[1:i]) for i in 1:N)
flatten!(f)
value(start_value, f)
```

This is such a rare case that can be easily worked around that I don't know if it's worth complicating the implementation of `_evaluate_expr` for.

**Comment by odow** [comment]
The other option is of course:
```julia
@variable(M, x[1:N], start = 0)
y = value.(start_value, x)
prod(sum(y[1:i]) for i in 1:N)
```

**Comment by mitchphillipson** [comment]
This is my solution, find the value first.

I see this as more of a documentation issue, of which this thread may be
sufficient. I didn't get any hits useful hits when I googled it. I'm in a
position where I know how to fix the issue, but I could see future users
getting confused.

**Comment by odow** [comment]
I don't even know if it is a documentation issue. 

Let's work through what this line is doing:
```julia
value(start_value,prod(sum(x[1:i]) for i in 1:N))
```

`prod(sum(x[1:i]) for i in 1:N)` is creating a `NonlinearExpr` of the product of 8,000 terms, where each term an `AffExpr` with up to 8,000 terms. Except that `prod` does not create the n-ary `*(args...)`, but instead works by folding the binary `*`: `prod(x) = foldl(*, x)`. So we create `*(sum(x[1:1]), *(sum(x[1:2], *( ... )))`. So we're actually creating something like 7,999 `NonlinearExpr` and a very unbalanced binary tree.

We then call `value(start_value, ...)`, which is going to recursively evaluate the expression, and will end up calling `start_value` `N - i + 1` times for each `x[i]` because we don't cache values. Even if we fixed the recession issue, this is a lot of operations!

The alternative is to compute `your = start_value.(x)`, which queries `start_value` once for each variable and returns a `Vector{Float64}`. Then your `prod` has a loop that computes `sum(x[1:i])` 8,000 times, and since slices copy, you are creating `8,000` new vectors. So you could be even more efficient with `prod(sum(@views(y[1:i])) for i in 1:N)`. But the output of `sum` is a `Float64`, so your `prod` is then the product of 8,000 `Float64` which is okay.

Also how sparse is the start value of `x`? Can you even compute a product of that many elements to the required precision?

**Comment by odow** [comment]
I'm tempted to close this as won't fix. I don't know if there is an easy fix for this.
