### ISSUE TITLE
Base.show(model) calling print on Jupyter

### ISSUE THREAD

**Issue by bbrunaud** [jump-dev/JuMP.jl#957]
Hello

Whenever a model is defined in Jupyter, the output is the full printout of the model, which can be annoying (many many lines of output). Is this the intended behavior?.

regards

Braulio

**Comment by mlubin** [comment]
If something is annoying, we're likely to accept a PR fixing it.

**Comment by blegat** [comment]
Jupyter is calling something like `show` on the result of the command. The fact that the Model prints itself when told to do so seems reasonable.
In any case, one can use `;` at the end of expression to avoid 
@bbrunaud Would you say that the printout of the model is too verbose ? Or that some function returns the model, triggering a full printout while they could return `nothing` ? Doing `m = Model()` displays the empty model, which is not a huge output.

**Comment by odow** [comment]
Ref #1180

**Comment by odow** [comment]
This is going to take some refactoring, because the issue is that we have a mix of `print` and `show`, a summary, a plain text model, and a LaTeX model.

In the REPL, `Julia> model` calls
https://github.com/jump-dev/JuMP.jl/blob/a171d750d0103304f2dbf1916202a69ab24bd5a9/src/print.jl#L152-L161

but in IJulia/Documenter, ending a cell with `model` calls
https://github.com/jump-dev/JuMP.jl/blob/a171d750d0103304f2dbf1916202a69ab24bd5a9/src/print.jl#L195-L197

but calling `print(model)` calls:
https://github.com/jump-dev/JuMP.jl/blob/a171d750d0103304f2dbf1916202a69ab24bd5a9/src/print.jl#L192-L194

To bring some sanity, I'd propose

* `Julia> model` or ending a cell with `model` prints the summary
* `print(model)` prints the model with all constraints in plain-text
* `print(model; latex = true)` prints the latex version of the model
  * In IJulia and documenter, this pretty prints in MathJax.
  * In the REPL, this prints a string that can be copy-pasted into a tex file. 

The only breaking change for this from a user-perspective is that models in IJulia would show a summary by default, and you'd have to use `print(model; latex = true)` to get the latex version.

### Proof-of-concept

```Julia
struct Model end

function _print_summary(io::IO, model::Model)
    print(io, "model summary")
end

function _print_model(io::IO, model::Model)
    print(io, "full model")
end

function _print_latex(io::IO, model::Model)
    print(io, "\$\$\\min Model + latex\$\$")
end


Base.show(io::IO, model::Model) = _print_summary(io, model)

struct LaTeXModel{T}
    model::T
end

function Base.show(io::IO, model::LaTeXModel)
    return print(io, sprint(_print_latex, model.model))
end

function Base.show(io::IO, ::MIME"text/latex", model::LaTeXModel)
    _print_latex(io, model.model)
end

function Base.print(io::IO, model::Model; latex::Bool = false)
    if latex
        return LaTeXModel(model)
    else
        _print_model(io, model)
    end
end

Base.print(model::Model; latex::Bool = false) = print(stdout, model; latex=latex)
```

### Output from IJulia

![image](https://user-images.githubusercontent.com/8177701/106842106-37e3b000-6708-11eb-8582-13fc4a2ea24c.png)

### Output from the REPL

![image](https://user-images.githubusercontent.com/8177701/106842118-40d48180-6708-11eb-8638-ef37ea156ec1.png)
